cuts = [ "after_preselection",
		   "after_onelep",
		   "after_twolep",
		   "after_onetrack",
		   #"after_onetrack_eeOS"  ,
		   #"after_onetrack_eeSS"  ,
		   #"after_onetrack_mumuOS",
		   #"after_onetrack_mumuSS",
		   #"after_onetrack_emu"   ,
		   #"after_Zveto",
		   #"after_Zveto_eeOS"  ,
		   #"after_Zveto_eeSS"  ,
		   #"after_Zveto_mumuOS",
		   #"after_Zveto_mumuSS",
		   #"after_Zveto_emu"   ,
		   #"after_bjet_veto",
		   #"after_bjet_veto_eeOS"  ,
		   #"after_bjet_veto_eeSS"  ,
		   #"after_bjet_veto_mumuOS",
		   #"after_bjet_veto_mumuSS",
		   #"after_bjet_veto_emu"   ,
		   "after_onetrack_MET_g50",
		   "after_onetrack_MET_g50_eeOS"  ,
		   "after_onetrack_MET_g50_eeSS"  ,
		   "after_onetrack_MET_g50_mumuOS",
		   "after_onetrack_MET_g50_mumuSS",
		   "after_onetrack_MET_g50_emu"   ]
		   #"after_etmiss100",
		   #"after_etmiss100_eeOS"  ,
		   #"after_etmiss100_eeSS"  ,
		   #"after_etmiss100_mumuOS",
		   #"after_etmiss100_mumuSS",
		   #"after_etmiss100_emu"]

cutnames = { "after_preselection": "Preselection",
             "initial": "initial",
             "initial_pileupSF": "initial pileupSF",
             "after_grl": "after grl",
             "after_trigger": "after trigger",
             "after_primvert": "after primvert",
             "after_LArVeto": "after LArVeto",
             "after_jetcleaning": "after jetcleaning",
             "after_LArError": "after LArError",
             "after_overlapremoval": "after overlapremoval",
             "after_triggerplateau": "Trigger Plateau",
             "after_onelep": "1 $\\ell$",
             "after_lepton_veto": "Lepton Veto",
             "after_jet_met_phi": "Delta Phi",
             "after_meff": "Effective mass",
             "after_QCD_CR": "QCD CR",
             "after_Wtop_CR": "Wtop CR",
             "after_QCD_CR_zerotau": "0 $\\tau$",
             "after_Wtop_CR_zerotau": "0 $\\tau$",
             "after_QCD_CR_onetau": "1 $\\tau$",
             "after_Wtop_CR_onetau": "1 $\\tau$",
             "after_QCD_CR_twotau": "2 $\\tau$",
             "after_Wtop_CR_twotau": "2 $\\tau$",
             "after_twolep": "2 $\\ell$",
             "after_onetrack": "1 track",
             "after_onetau": "1 $\\tau$",
             "after_twotau": "2 $\\tau$",
             "after_trilep": "3 $\\ell$",
             "after_MT": "$\displaystyle\sum m_{T} \geq 100$ GeV",
             "after_HT600_MT": "H$_{T} \geq 600$ GeV",
             "after_onetrack_eeOS":   "\\,\\,1 track eeOS  ",
             "after_onetrack_eeSS":   "\\,\\,1 track eeSS  ",
             "after_onetrack_mumuOS": "\\,\\,1 track mumuOS",
             "after_onetrack_mumuSS": "\\,\\,1 track mumuSS",
             "after_onetrack_emu"   : "\\,\\,1 track emu   ",
             "after_sfos":"SFOS",
             "after_Zveto":"Z veto",
             "after_Zveto_eeOS"  : "\\,\\,Z veto eeOS  ",
             "after_Zveto_eeSS"  : "\\,\\,Z veto eeSS  ",
             "after_Zveto_mumuOS": "\\,\\,Z veto mumuOS",
             "after_Zveto_mumuSS": "\\,\\,Z veto mumuSS",
             "after_Zveto_emu"   : "\\,\\,Z veto emu   ",
             "after_bjet_veto": "b-jet veto",
             "after_bjet_veto_eeOS"  : "\\,\\,b-jet veto eeOS  ",
             "after_bjet_veto_eeSS"  : "\\,\\,b-jet veto eeSS  ",
             "after_bjet_veto_mumuOS": "\\,\\,b-jet veto mumuOS",
             "after_bjet_veto_mumuSS": "\\,\\,b-jet veto mumuSS",
             "after_bjet_veto_emu"   : "\\,\\,b-jet veto emu   ",
             "after_onetrack_MET_g50": "1 track MET $>$ 50 GeV",
             "after_onetrack_MET_g50_eeOS"  : "\\,\\,MET $>$ 50 GeV eeOS  ",
             "after_onetrack_MET_g50_eeSS"  : "\\,\\,MET $>$ 50 GeV eeSS  ",
             "after_onetrack_MET_g50_mumuOS": "\\,\\,MET $>$ 50 GeV mumuOS",
             "after_onetrack_MET_g50_mumuSS": "\\,\\,MET $>$ 50 GeV mumuSS",
             "after_onetrack_MET_g50_emu"   : "\\,\\,MET $>$ 50 GeV emu   ",
             "after_MET_g50": "MET $>$ 50 GeV",
             "after_trilep_MET_g50": " 3$\\ell$, MET $>$ 50 GeV",
             "after_trilep_MET_g50_eeOS"  : "\\,\\,MET $>$ 50 GeV eeOS  ",
             "after_trilep_MET_g50_eeSS"  : "\\,\\,MET $>$ 50 GeV eeSS  ",
             "after_trilep_MET_g50_mumuOS": "\\,\\,MET $>$ 50 GeV mumuOS",
             "after_trilep_MET_g50_mumuSS": "\\,\\,MET $>$ 50 GeV mumuSS",
             "after_trilep_MET_g50_emu"   : "\\,\\,MET $>$ 50 GeV emu   ",
             "after_etmiss100":"MET $>$ 100 GeV",
             "after_etmiss100_eeOS"  : "\\,\\,MET $>$ 100 GeV eeOS  ",
             "after_etmiss100_eeSS"  : "\\,\\,MET $>$ 100 GeV eeSS  ",
             "after_etmiss100_mumuOS": "\\,\\,MET $>$ 100 GeV mumuOS",
             "after_etmiss100_mumuSS": "\\,\\,MET $>$ 100 GeV mumuSS",
             "after_etmiss100_emu"   : "\\,\\,MET $>$ 100 GeV emu   "}

cutindices= { "_after_preselection": "0",
		   "_after_onelep": "1",
		   "_after_twolep": "2",
		   "_after_trilep": "3",
		   "_after_sfos":"4",
		   "_after_Zveto":"5",
		   "_after_bjet_veto":"6",
		   "_after_MET_g50": "7",
		   }

flavours = ["_eeOS", "_eeSS", "_mumuOS", "_mumuSS", "_emu"]

cuts_no_flavour = [
			#"after_preselection",
		   #"after_onelep",
		   #"after_twolep",
		   "after_trilep",
		   "after_sfos",
		   "after_Zveto",
		   "after_bjet_veto",
		   "after_MET_g50"
		   ]


cuts_ditau = [
#    "initial",
    "after_preselection",
    "after_lepton_veto",
    "after_onetau",
    "after_twotau",
    "after_jet_met_phi",
    "after_MT",
    "after_HT600_MT",

    ]


cuts_ditau_CR = [
"after_QCD_CR",
"after_QCD_CR_zerotau",
"after_QCD_CR_onetau",
"after_QCD_CR_twotau",
"after_Wtop_CR",
"after_Wtop_CR_zerotau",
"after_Wtop_CR_onetau",
"after_Wtop_CR_twotau",
    ]

cuts_ditau_data = [
    "after_triggerplateau",
    "after_lepton_veto",
    "after_onetau",
    "after_twotau",
    "after_jet_met_phi",
    "after_MT",
    "after_HT600_MT",

    ]
