import ROOT
ROOT.gROOT.SetBatch()
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetOptTitle(0)
#import PlotExample
from math import fabs
import cutlist

def color(file):
	filename = str(file.GetName())
	if "pythia_jetjet" in filename:
		return ROOT.kYellow
	elif "Dibosons" in filename:
		return ROOT.kGray
	elif "DY" in filename:
		return ROOT.kPink+1
	elif "Top" in filename:
		return ROOT.kGreen-9
	elif "Zjets" in filename:
		return ROOT.kAzure+1
	elif "Wjets" in filename:
		return ROOT.kGreen
	else:
		return ROOT.kBlack

def getMaxMin(hist): 

	histcloneMax = hist.Clone("histcloneMax"); histcloneMin = hist.Clone("histcloneMin")
	for i in xrange(hist.GetNbinsX()+1):
		central=hist.GetBinContent(i)
		if(central==0):
			continue
		histcloneMax.SetBinContent(i,central); histcloneMax.SetBinError(i,central)
		histcloneMin.SetBinContent(i,central); histcloneMin.SetBinError(i,central)
		#hist.SetBinError(i,fabs(nBINS[i][0]));
		#histcloneMax2.SetBinContent(i,central); histcloneMax2.SetBinError(i,sqrt(central))
		#histcloneMin2.SetBinContent(i,central); histcloneMin2.SetBinError(i,sqrt(central))
		totalmc_SysErr = ROOT.TGraphAsymmErrors( histcloneMax, histcloneMin)
		totalmc_SysErr.SetFillColor(kYellow)
		return totalmc_SysErr 

def plot(hist_name, cut, hist_min, hist_max, file_1, file_2, file_3, file_4, file_5, file_6, data, mc_file, signal_1, signal_2, xrange=False, xmin=0, xmax=600):
	c1 = ROOT.TCanvas("c1","Example",800,600)
	mainPad = ROOT.TPad("","",0.00,0.26,1.,1.)
	mainPad.SetNumber(1)
	mainPad.Draw()
	mainPad.cd()
	hs1 = ROOT.THStack("hs1", "stack" + hist_name + cut)
	mainPad.Clear()
	mainPad.SetLogy()
	print file_1.GetName()
	file_1.cd(); hist = file_1.Get(hist_name+cut); hist.SetFillColor(color(file_1)); hs1.Add(hist)
	file_2.cd(); hist = file_2.Get(hist_name+cut); hist.SetFillColor(color(file_2)); hs1.Add(hist)
	file_3.cd(); hist = file_3.Get(hist_name+cut); hist.SetFillColor(color(file_3)); hs1.Add(hist)
	file_4.cd(); hist = file_4.Get(hist_name+cut); hist.SetFillColor(color(file_4)); hs1.Add(hist)
	file_5.cd(); hist = file_5.Get(hist_name+cut); hist.SetFillColor(color(file_5)); hs1.Add(hist)
	file_6.cd(); hist = file_6.Get(hist_name+cut); hist.SetFillColor(color(file_6)); hs1.Add(hist)
	hs1.Draw("hist")
	hs1.GetYaxis().SetTitle("Entries/10 GeV")
	hs1.SetMinimum(hist_min)
	hs1.SetMaximum(hist_max)
	if (xrange):
		hs1.GetXaxis().SetRangeUser(xmin,xmax)
	data.cd(); hist = data.Get(hist_name+cut); hist.SetLineColor(ROOT.kBlack); hist.SetMarkerStyle(20); hist.SetMarkerSize(0.5); hist.Draw("p e same");
	signal_1.cd(); hist = signal_1.Get(hist_name+cut); hist.SetLineColor(ROOT.kRed); hist.SetLineWidth(4);hist.Draw("same hist")
	signal_2.cd(); hist = signal_2.Get(hist_name+cut); hist.SetLineColor(ROOT.kBlue+3);hist.SetLineWidth(4); hist.Draw("same hist")
	#hs1.Draw("hist same")
	legend.Draw("same")
	totalmc = mc_file.Get(hist_name+cut)
	#mccloneMax = totalmc->Clone("mccloneMax"); mccloneMin = totalmc->Clone("mccloneMin")
	dataNom = data_file.Get(hist_name+cut)
	
	c1.cd()
	ratioPad = ROOT.TPad("","",0.00,0.00,1.,0.25)
	ratioPad.SetBottomMargin(-1.32)
	ratioPad.SetNumber(2)
	ratioPad.Draw()
	ratioPad.SetGridy()
	#ratioPad.SetLogy()
	ratioPad.cd()
	totalmcRatio = dataNom.Clone("totalmcRatio");  #totalmcRatio.Sumw2()
	totalmcRatio.SetMarkerSize(1.2); totalmcRatio.SetLineWidth(2);  totalmcRatio.SetLineColor(ROOT.kBlack)
	totalmcRatio.Divide( totalmc )
	#totalmcRatio.GetYaxis().SetTitleOffset(0.5)
	totalmcRatio.GetYaxis().SetTitleSize(0.12); totalmcRatio.GetYaxis().SetTitle("Data/MC")
	#totalmcRatio.GetXaxis().SetTitleSize(0.12); totalmcRatio.GetXaxis().SetTitleOffset(1);  totalmcRatio.GetXaxis().SetTitle(totalmc.GetXaxis().GetTitle())
	#totalmcRatio.GetYaxis().SetLabelSize(0.12); totalmcRatio.GetXaxis().SetLabelSize(0.12)
	totalmcRatio.GetYaxis().SetNdivisions(505)
	if (xrange):
		totalmcRatio.GetXaxis().SetRangeUser(xmin,xmax)
	
	totalmcRatio.Draw("pe")
	totalmcRatio.Draw("pe same");  #totalmcRatio.Draw("axis same");  totalmcRatio.Draw("axiG same")
	c1.cd()
	c1.Draw()
	c1.Print(hist_name + "_" + cutlist.cutindices[cut] + cut + "_ratio.png")

def flavour_plot(hist_name, cut, hist_min, hist_max, canvas, file_1, file_2, file_3, file_4, file_5, file_6, data, signal_1, signal_2, xrange=False, xmin=0, xmax=600):
	for flavour in cutlist.flavours:
		plot(hist_name, cut+flavour, hist_min, hist_max, canvas, file_1, file_2, file_3, file_4, file_5, file_6, data, signal_1, signal_2, xrange=False, xmin=0, xmax=600)


legend = ROOT.TLegend(.65,.55,.85,.75)
legend.SetFillColor(0)
legend.SetMargin(0.5)

data_file = ROOT.TFile("Data.root"); data_file.cd();
mc_file = ROOT.TFile("MC_doTruthMatch_169.0pb.root"); mc_file.cd();
ttbar_file = ROOT.TFile("Top_doTruthMatch_169.0pb.root")
Wjets_file = ROOT.TFile("Wjets_doTruthMatch_169.0pb.root")
Zjets_file = ROOT.TFile("Zjets_doTruthMatch_169.0pb.root")
QCD_file = ROOT.TFile("pythia_jetjet_doTruthMatch_169.0pb.root")
dibosons_file = ROOT.TFile("Dibosons_doTruthMatch_169.0pb.root")
drellyan_file = ROOT.TFile("DY_doTruthMatch_169.0pb.root")
DG1_file = ROOT.TFile("MC.138421.DGemt_TB6_M12U_100_100_100_doTruthMatch_169.0pb.root")
DG2_file = ROOT.TFile("MC.138543.DGemt_TB6_M12U_250_140_140_doTruthMatch_169.0pb.root")
QCD_file.cd(); hist = QCD_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "QCD")
ttbar_file.cd(); hist = ttbar_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "t#bar{t}")
Wjets_file.cd(); hist = Wjets_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "W + jets")
Zjets_file.cd(); hist = Zjets_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "Z + jets")
dibosons_file.cd(); hist = dibosons_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "dibosons")
drellyan_file.cd(); hist = drellyan_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "Drell Yan")
data_file.cd(); hist = data_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "data")
DG1_file.cd(); hist = DG1_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "DG1")
DG2_file.cd(); hist = DG2_file.Get("Mt_after_preselection"); legend.AddEntry(hist, "DG2")

#plot("MET", "_after_twolep", 0, 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0,500)
#plot("MET", "_after_onetrack", 1, 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0,500)

plot("Mt", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mt", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mt", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mt", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mt", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mt", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mt", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("MET", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#plot("MET", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#plot("MET", "_after_twolep", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#plot("MET", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#plot("MET", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#plot("MET", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#plot("MET", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#plot("MET", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#flavour_plot("MET", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#flavour_plot("MET", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#flavour_plot("MET", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#flavour_plot("MET", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#flavour_plot("MET", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 900)
#
#plot("Meff", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Meff", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Meff", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Meff", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Meff", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Meff", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Meff", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Meff", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Meff", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Meff", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Meff", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Meff", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Meff", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Elec_N", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_N", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_N", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_N", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_N", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_N", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_N", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_N", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_N", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_N", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_N", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_N", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_N", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Elec_Pt", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_Pt", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_Pt", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_Pt", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_Pt", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_Pt", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_Pt", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Elec_Pt", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_Pt", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_Pt", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_Pt", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_Pt", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Elec_Pt", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Muon_N", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Muon_N", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Muon_N", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Muon_N", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_N", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_N", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_N", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_N", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_N", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Muon_Pt", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Muon_Pt", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Muon_Pt", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Muon_Pt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_Pt", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_Pt", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_Pt", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_Pt", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Muon_Pt", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Lep_N", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_N", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_N", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_N", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_N", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_N", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_N", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_N", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_N", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Lep_Pt", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_Pt", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_Pt", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_Pt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_Pt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Lep_Pt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_Pt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_Pt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_Pt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_Pt", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Lep_Pt", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Track_N", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_N", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_N", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_N", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_N", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_N", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_N", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Track_Pt", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_Pt", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_Pt", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
plot("Track_Pt", "_after_twolep", 0.1, 1e6, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 400)
#plot("Track_Pt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_Pt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
plot("Track_Pt", "_after_Zveto", 0.1, 1e6, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 400)
#plot("Track_Pt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
plot("Track_Pt", "_after_bjet_veto", 0.1, 1e6, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0, 400)
#plot("Track_Pt", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_Pt", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_Pt", "_after_twolep", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0,400)
#flavour_plot("Track_Pt", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_Pt", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_Pt", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_Pt", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_Pt", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Track_PtCone20", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Track_PtCone20_over_Pt", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20_over_Pt", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20_over_Pt", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file, True, 0,200)
#plot("Track_PtCone20_over_Pt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20_over_Pt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20_over_Pt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20_over_Pt", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Track_PtCone20_over_Pt", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20_over_Pt", "_after_onetrack", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20_over_Pt", "_after_Zveto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20_over_Pt", "_after_bjet_veto", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20_over_Pt", "_after_etmiss50", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Track_PtCone20_over_Pt", "_after_etmiss100", 0.1, 1e5, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Jet_N", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_N", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_N", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_N", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_N", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_N", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_N", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_N", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_N", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_N", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_N", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_N", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_N", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Jet_Pt", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_Pt", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_Pt", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_Pt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_Pt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_Pt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_Pt", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Jet_Pt", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_Pt", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_Pt", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_Pt", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_Pt", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Jet_Pt", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Melel", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Melel", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Melel", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Melel", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Melel", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Melel", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Melel", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Melel", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Melel", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Melel", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Melel", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Melel", "_after_etmiss50", 0.1, 1e3, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Melel", "_after_etmiss100", 0.1, 1e3, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Mmumu", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mmumu", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mmumu", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mmumu", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mmumu", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mmumu", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mmumu", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mmumu", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mmumu", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mmumu", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mmumu", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mmumu", "_after_etmiss50", 0.1, 1e3, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mmumu", "_after_etmiss100", 0.1, 1e3, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#
#plot("Mll", "_after_preselection", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mll", "_after_onelep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mll", "_after_twolep", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mll", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mll", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mll", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mll", "_after_etmiss50", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#plot("Mll", "_after_etmiss100", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mll", "_after_onetrack", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mll", "_after_Zveto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mll", "_after_bjet_veto", 0.1, 1e7, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mll", "_after_etmiss50", 0.1, 1e3, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)
#flavour_plot("Mll", "_after_etmiss100", 0.1, 1e3, dibosons_file, drellyan_file, ttbar_file, Zjets_file, Wjets_file, QCD_file, data_file, mc_file, DG1_file, DG2_file)


